<div class="footer">
  <div class="container">
    <p class="nav">
      <span><a href="http://www.gizwits.com">{{ __("home") }}</a></span>
      <span><a href="http://www.gizwits.com/about-us">{{ __("about") }}</a></span>
      <span><a href="http://www.gizwits.com/about-us#contact-us">{{ __("contact") }}</a></span>
      <span><a href="">{{ __("join") }}</a></span>
    </p>
    <p class="footnote">&#169;2011-2016; Gizwits IoT Technology Co., Ltd. 粤ICP备11090211号</p>
  </div>
</div>