<div class="footer">
  <div class="container">
    <p class="nav">
      <span><a href="http://www.gizwits.com" target="_blank">{{ __("home") }}</a></span>
      <span><a href="http://www.gizwits.com/about-us" target="_blank">{{ __("about") }}</a></span>
      <span><a href="http://www.gizwits.com/about-us#contact-us" target="_blank">{{ __("contact") }}</a></span>
      <span><a href="http://www.gizwits.com/talent/social" target="_blank">{{ __("join") }}</a></span>
    </p>
    <p class="footnote">&#169;2011-2016; Gizwits IoT Technology Co., Ltd. 粤ICP备11090211号</p>
  </div>
</div>