<span class="widget">
  <a class="edit-link" target="_blank" title="{{ __('edit') }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
  <a href="https://github.com/gizwits-docs/gizwits-docs/issues" target="_blank" title="{{ __('feedback') }}"><i class="fa fa-github" aria-hidden="true"></i></a>
  <a href="#" title="{{ __('scrolltop') }}"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
</span>