<div class="body">
  
  <div class="container clearfix">
    <div class="navigation">
      <div class="nav"></div>
    </div>
    <div class="markdown-body" data-spy="scroll" data-target=".navigation">
      <div class="heading">
        <span class="title">{{ page.title }}</span>
        <a class="edit-link" target="_blank"><i class="fa fa-github" aria-hidden="true"></i> {{ __('edit') }}</a>
      </div>
      {{ page.content }}
    </div>
  </div>
</div>