<div class="body">
  <div class="container pure-g">
    <div class="navigation pure-u-8-24"></div>
    <div class="markdown-body pure-u-16-24">
      <div class="title">{{ page.title }}</div>
      <div>
        <a href="https://github.com/gizwits-docs/gizwits-docs/issues">{{ __('issues') }}</a>
        <br>
        <a class="edit-link" target="_blank">{{ __('edit') }}</a>
      </div>
      {{ page.content }}
    </div>
  </div>
</div>